FROM node:20-alpine

WORKDIR /app

# Install dependencies
RUN npm install -g typescript ts-node
RUN npm install ws @types/ws

# Copy simulator script
COPY ocpp-client-simulator.ts .

CMD ["ts-node", "ocpp-client-simulator.ts"]
